# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token e3a901208fae1302a507e3521ee2c8693c14cd25
###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

{
  "title": "кресло IKEA",
  "description": "Срочно продам стол"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/25/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

{
  "status": "DRAFT"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-10-01
Content-Type: application/json

###

# фильтрация по статусу
GET {{baseUrl}}/advertisements/?status=OPEN
Content-Type: application/json
# Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

###

# получение избранных объявлений
GET {{baseUrl}}/advertisements/favorite_advertisements/
Content-Type: application/json
Authorization: Token e3a901208fae1302a507e3521ee2c8693c14cd25

###

# добавление объявления в избранное
POST {{baseUrl}}/advertisements/13/add_to_favorite/
Content-Type: application/json
Authorization: Token e3a901208fae1302a507e3521ee2c8693c14cd25
