# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

{
  "title": "кресло IKEA",
  "description": "Срочно продам стол"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/16/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

{
  "status": "OPEN"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/9/
Content-Type: application/json
Authorization: Token e30e9e796374ac770cbebc4ed843331236282b5e

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-10-01
Content-Type: application/json


e30e9e796374ac770cbebc4ed843331236282b5e