# Generated by Django 5.2.8 on 2025-11-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_status_userfavoriteadvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoriteadvertisement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено в избранное:'),
        ),
    ]
