# Generated by Django 5.2.7 on 2025-10-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_of_measure',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время измерения'),
        ),
    ]
