# Generated by Django 5.2.7 on 2025-10-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_date_of_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение с измерением'),
        ),
    ]
